# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Castellanos & asociados
email: contacto@castellanosasociados.com
description: Firma de abogados con más de treinta años de experiencia en derecho contencioso administrativo y constitucional.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://castellanosasociados.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
tel1: (55) 55 24 24 14
tel2: (55) 55 34 71 77

# Build settings
markdown: kramdown

collections:
  - abogados
